# Generated by Django 6.0.5 on 2026-06-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('link', models.URLField(max_length=1000, unique=True, verbose_name='Đường dẫn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('pub_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngày đăng gốc')),
                ('pub_date_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đăng định dạng chuẩn')),
                ('creator', models.CharField(default='Vogue', max_length=200, verbose_name='Tác giả')),
                ('image', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Hình ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-pub_date_parsed', '-created_at'],
            },
        ),
    ]
