# Generated by Django 6.0.5 on 2026-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_voucher_order_discount_amount_order_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
